<?php

namespace backend\controllers;


use Yii;
use yii\rest\Controller;
use yii\filters\VerbFilter;

use common\models\Course;
class CartController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            'verbs'=>[
                'count'=>['get'],
                'total'=>['get'],
                'add'=>['post']
            ]
        ];
    }

    public function actionCount()
    {
        $session =Yii::$app->session;
        $count=0;
        if($session->has('cart')){
            $cart=$session->get('cart');
            $count=count($cart);
        }
        return parent::actions(); // TODO: Change the autogenerated stub
    }
 public function actionAdd()
 {
     $request =Yii::$app->request;
     $session=Yii::$app->session;
     if($session->isPost){
         $course_id=$request->post('id');

     }
     return parent::actions(); // TODO: Change the autogenerated stub
 }

    public function actionIndex()
    {
        return $this->render('index');
    }

}
